import React, { useEffect, useRef, useState } from 'react';
import L from 'leaflet';
import { NodeId, TimelineFrame } from '../types';
import { NODES_LIST } from '../data/nodesData';
import { Info } from 'lucide-react';
interface MapViewProps { selectedNodeId: NodeId; onSelectNode: (nodeId: NodeId) => void; currentFrame: TimelineFrame; radarVisible: boolean; nodesVisible: boolean; onOpenNodeDetail: (nodeId: NodeId) => void; }
const GRID_HALF_STEP = .125;
export const MapView: React.FC<MapViewProps> = ({ selectedNodeId, onSelectNode, currentFrame, radarVisible, nodesVisible, onOpenNodeDetail }) => {
  const container = useRef<HTMLDivElement>(null); const mapRef = useRef<L.Map | null>(null); const cells = useRef<Record<string, L.Rectangle>>({}); const markers = useRef<Record<string, L.Marker>>({}); const [hovered, setHovered] = useState<NodeId | null>(null);
  useEffect(() => { if (!container.current || mapRef.current) return; const map = L.map(container.current, { center: [-6.75, 107], zoom: 10, minZoom: 9, maxZoom: 14, zoomControl: false }); L.control.zoom({ position: 'topright' }).addTo(map); L.tileLayer('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png', { attribution: '&copy; CARTO &copy; OpenStreetMap' }).addTo(map); mapRef.current = map; return () => { map.remove(); mapRef.current = null; }; }, []);
  useEffect(() => { const map = mapRef.current; if (!map) return; if (!radarVisible) { Object.values(cells.current).forEach((cell: L.Rectangle) => cell.remove()); cells.current = {}; return; } Object.values(NODES_LIST).forEach((node) => { const rain = currentFrame.telemetries[node.id]?.rainIntensityMmH ?? 0; const bounds: L.LatLngBoundsExpression = [[node.lat - GRID_HALF_STEP, node.lng - GRID_HALF_STEP], [node.lat + GRID_HALF_STEP, node.lng + GRID_HALF_STEP]]; const style = { color: rain >= 10 ? '#b96a4b' : rain >= 2 ? '#bc8a35' : '#4d897c', fillOpacity: .16, weight: 1 }; const existing = cells.current[node.id]; if (existing) { existing.setStyle(style); existing.setBounds(bounds); } else cells.current[node.id] = L.rectangle(bounds, style).bindTooltip(`<strong>${node.id}</strong><br>${rain.toFixed(1)} mm/jam<br><small>Contoh sel ERA5</small>`).addTo(map); }); }, [radarVisible, currentFrame]);
  useEffect(() => { const map = mapRef.current; if (!map) return; if (!nodesVisible) { Object.values(markers.current).forEach((marker: L.Marker) => marker.remove()); markers.current = {}; return; } Object.values(NODES_LIST).forEach((node) => { const rain = currentFrame.telemetries[node.id]?.rainIntensityMmH ?? 0; const icon = L.divIcon({ html: `<div class="era5-node ${selectedNodeId === node.id ? 'is-selected' : ''}"><span class="era5-node__dot"></span><span class="era5-node__label"><b>${node.id}</b> ${rain.toFixed(1)} mm/jam</span></div>`, className: 'era5-node-icon', iconSize: [130, 44], iconAnchor: [65, 11] }); const existing = markers.current[node.id]; if (existing) existing.setIcon(icon); else { const marker = L.marker([node.lat, node.lng], { icon }).addTo(map); marker.on('click', () => onSelectNode(node.id)); marker.on('mouseover', () => setHovered(node.id)); marker.on('mouseout', () => setHovered(null)); markers.current[node.id] = marker; } }); }, [nodesVisible, selectedNodeId, currentFrame, onSelectNode]);
  const active = hovered ? NODES_LIST[hovered] : null; const telemetry = hovered ? currentFrame.telemetries[hovered] : null;
  return <div role="region" aria-label="Peta contoh lima sel ERA5" className="era5-map relative w-full h-full min-h-[420px] border border-[#c9cec4] bg-[#dfe6dd]"><div ref={container} className="w-full h-full" /><div className="absolute top-4 left-4 pointer-events-none z-10"><div className="era5-map-card"><p className="era5-map-card__eyebrow">Lima sel ERA5</p><p className="era5-map-card__title">Contoh intensitas hujan per sel.</p><p className="era5-map-card__detail">Bukan radar atau data waktu nyata.</p></div></div>{active && telemetry && <div className="era5-hover-card"><div className="flex justify-between"><div><p className="font-mono-data text-[11px]">{active.id}</p><p className="text-xs">{active.locationName}</p></div><button onClick={() => onOpenNodeDetail(active.id)} aria-label={`Detail ${active.id}`}><Info className="w-4 h-4" /></button></div><p className="text-xs mt-2">Presipitasi contoh: {telemetry.rainIntensityMmH.toFixed(1)} mm/jam</p></div>}</div>;
};
