import React, { useEffect, useRef } from 'react';
import { NodeId, TimelineFrame } from '../types';
import { NODES_LIST } from '../data/nodesData';
import { X, MapPin, Thermometer, Droplets, Wind, Gauge, Shield } from 'lucide-react';

interface NodeDetailModalProps { nodeId: NodeId | null; frame: TimelineFrame; onClose: () => void; }
export const NodeDetailModal: React.FC<NodeDetailModalProps> = ({ nodeId, frame, onClose }) => {
  const modalRef = useRef<HTMLDivElement>(null);
  useEffect(() => { if (!nodeId) return; modalRef.current?.focus(); const close = (event: KeyboardEvent) => event.key === 'Escape' && onClose(); window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close); }, [nodeId, onClose]);
  if (!nodeId) return null; const node = NODES_LIST[nodeId]; const telemetry = frame.telemetries[nodeId]; if (!telemetry) return null;
  const fields = [[Droplets, 'Presipitasi', `${telemetry.rainIntensityMmH.toFixed(1)} mm/jam`], [Thermometer, 'Suhu', `${telemetry.tempCelsius.toFixed(1)} °C`], [Wind, 'Kecepatan angin', `${telemetry.windSpeedKmh} km/jam`], [Gauge, 'Tekanan', `${telemetry.pressureHpa} hPa`], [Shield, 'Kelembapan', `${telemetry.humidityPercent}%`]] as const;
  return <div className="fixed inset-0 z-50 bg-[#060b14]/85 backdrop-blur-xl flex items-center justify-center p-4"><div ref={modalRef} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby="node-detail-modal-title" className="glass-panel w-full max-w-xl p-6 relative bg-[#0b1326]/95 focus:outline-none"><button onClick={onClose} className="absolute top-4 right-4" aria-label="Tutup detail simpul"><X className="w-5 h-5" /></button><div className="mb-5 pb-4 border-b border-white/10"><h2 id="node-detail-modal-title" className="font-headline text-lg font-bold text-[#dbfcff]">Sel ERA5: {node.name}</h2><p className="text-xs text-[#849495] flex gap-1.5 mt-1"><MapPin className="w-3.5 h-3.5" />{node.locationName} ({node.role})</p></div><div className="grid grid-cols-3 gap-2 mb-5 p-3.5 bg-[#131b2e] text-xs"><span>Lat: {node.lat.toFixed(4)}°</span><span>Lng: {node.lng.toFixed(4)}°</span><span>Elevasi: {node.elevation} mdpl</span></div><p className="text-[10px] text-[#849495] mb-3">Nilai contoh statis ({frame.timeWib})</p><div className="grid grid-cols-2 sm:grid-cols-3 gap-3">{fields.map(([Icon, label, value]) => <div key={label} className="p-3 bg-[#171f33] border border-white/5"><div className="text-[10px] text-[#849495]"><Icon className="w-3 h-3 inline" /> {label}</div><div className="font-mono-data text-sm text-[#dae2fd] mt-1">{value}</div></div>)}</div></div></div>;
};
