import React, { useMemo } from 'react';
import { HistoricalAnalog } from '../types';
import { HISTORICAL_ANALOGS } from '../data/historicalAnalogs';
import { Database, ArrowUpRight, CloudRain, Wind, Thermometer, Droplets } from 'lucide-react';

interface RetrievalAnalogsPanelProps { onSelectAnalog?: (analog: HistoricalAnalog) => void; onOpenAll?: () => void; limitK?: number; }
export const RetrievalAnalogsPanel: React.FC<RetrievalAnalogsPanelProps> = ({ onSelectAnalog, onOpenAll, limitK = 3 }) => {
  const samples = useMemo(() => HISTORICAL_ANALOGS.slice(0, limitK), [limitK]);
  return <div className="w-full"><div className="flex flex-wrap items-center justify-between gap-2 mb-3"><div className="flex items-center gap-2"><Database className="w-4 h-4 text-[#00f0ff]" /><div><h3 className="font-mono-data text-xs font-bold text-[#dae2fd] uppercase tracking-wider">PERBANDINGAN SAMPEL (k={limitK}) <span className="text-[10px] font-normal text-[#00f0ff]">IndexFlatL2</span></h3><p className="text-[10px] font-mono-data text-[#849495] mt-0.5">Fixture perbandingan; tidak ada query atau indeks yang dieksekusi.</p></div></div>{onOpenAll && <button onClick={onOpenAll} className="text-[11px] font-mono-data text-[#00f0ff] hover:underline">Lihat semua <ArrowUpRight className="w-3 h-3 inline" /></button>}</div><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">{samples.map((sample, index) => <button key={sample.id} onClick={() => onSelectAnalog?.(sample)} className="text-left bg-[#131b2e]/80 rounded-xl border border-white/10 p-3 hover:border-[#00f0ff]/60"><div className="flex justify-between mb-2"><span className="font-mono-data text-[10px] text-[#00f0ff]">#{sample.rank ?? index + 1} SAMPEL</span><span className="font-mono-data text-[11px] text-[#dae2fd]">{sample.datetime}</span></div><span className="text-[10px] text-[#b9cacb]">{sample.patternType}</span><div className="my-3 text-xs font-mono-data text-[#00f0ff]">Skor perbandingan: {sample.similarityPercent.toFixed(1)}% {sample.distanceL2 !== undefined && `• L2 ${sample.distanceL2.toFixed(3)}`}</div><div className="grid grid-cols-2 gap-1.5 text-[10px] text-[#b9cacb]"><span><CloudRain className="w-3 h-3 inline" /> {sample.rainRateMmH} mm/jam</span><span><Wind className="w-3 h-3 inline" /> {sample.peakWindKmh} km/jam</span><span><Thermometer className="w-3 h-3 inline" /> {sample.tempCelsius}°C</span><span><Droplets className="w-3 h-3 inline" /> {sample.humidityPercent}%</span></div><p className="mt-3 pt-2 border-t border-white/5 text-[10px] text-[#b9cacb]">{sample.outcomeSummary}</p></button>)}</div></div>;
};
