import React, { useMemo, useState } from 'react';
import { Search, Menu, X, Check, MapPin } from 'lucide-react';
import { NodeId, ActiveTab } from '../types';
import { NODES_LIST } from '../data/nodesData';
interface TopAppBarProps { activeTab: ActiveTab; onSelectTab: (tab: ActiveTab) => void; radarVisible: boolean; onToggleRadar: () => void; nodesVisible: boolean; onToggleNodes: () => void; onSelectNode: (nodeId: NodeId) => void; onOpenTopologyModal: () => void; }
export const TopAppBar: React.FC<TopAppBarProps> = ({ activeTab, onSelectTab, radarVisible, onToggleRadar, nodesVisible, onToggleNodes, onSelectNode, onOpenTopologyModal }) => {
  const [query, setQuery] = useState(''); const [mobile, setMobile] = useState(false); const nodes = useMemo(() => Object.values(NODES_LIST).filter((node) => node.name.toLowerCase().includes(query.toLowerCase()) || node.locationName.toLowerCase().includes(query.toLowerCase())), [query]);
  const choose = (id: NodeId) => { onSelectNode(id); onSelectTab('map'); setQuery(''); };
  return <header className="fixed top-0 right-0 left-0 md:left-[72px] z-40 bg-[#f4f1e9] border-b border-[#d8d4c8] flex justify-between items-center px-4 md:px-6 h-[64px]"><div className="flex items-center gap-3"><button onClick={() => setMobile((value) => !value)} className="md:hidden" aria-label="Menu">{mobile ? <X /> : <Menu />}</button><button onClick={() => onSelectTab('map')} className="text-left"><h1 className="font-headline text-lg md:text-xl font-bold text-[#202720]">Pangrango Weather Desk</h1><span className="text-[10px] font-mono-data text-[#1f6056]">DEMONSTRASI ERA5</span></button></div><div className="hidden md:flex gap-2"><button onClick={onToggleRadar} aria-pressed={radarVisible} className="px-3 py-1.5 border text-[10px] font-mono-data"><Check className="w-3 h-3 inline" /> SEL ERA5 (5)</button><button onClick={onToggleNodes} aria-pressed={nodesVisible} className="px-3 py-1.5 border text-[10px] font-mono-data">SIMPUL</button><button onClick={onOpenTopologyModal} className="px-3 py-1.5 border text-[10px] font-mono-data">TOPOLOGI</button></div><div className="relative hidden sm:block"><Search className="w-4 h-4 absolute left-2 top-2 text-[#849495]" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Cari sel ERA5" className="pl-8 py-1.5 text-xs w-[180px] border" />{query && <div className="absolute right-0 top-9 w-[240px] bg-white border p-1">{nodes.map((node) => <button key={node.id} onClick={() => choose(node.id)} className="w-full text-left p-2 text-xs"><MapPin className="w-3 h-3 inline" /> {node.name} — {node.elevation} mdpl</button>)}</div>}</div>{mobile && <div className="absolute top-[64px] left-0 right-0 bg-white border p-3 md:hidden flex gap-2"><button onClick={() => onSelectTab('map')}>MAP</button><button onClick={() => onSelectTab('forecast')}>CHART</button><button onClick={() => onSelectTab('comparison')}>SAMPEL</button><button onClick={() => onSelectTab('eval')}>EVAL</button><button onClick={onOpenTopologyModal}>TOPOLOGI</button></div>}</header>;
};
